USE timestampmanagement;

SET ANSI_NULLS ON  
GO  
  
SET QUOTED_IDENTIFIER ON  
GO  
  
SET ANSI_PADDING ON  
GO  
  
CREATE TABLE[dbo]. [tblRole](  
  [role_id][int] IDENTITY(1,1) NOT NULL,  
  [role_name][varchar](50) NOT NULL,
  CONSTRAINT[PK_tblRole] PRIMARY KEY CLUSTERED(  
    [role_id] ASC 
  ) WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]  
) ON[PRIMARY]  
  
GO  
  
SET ANSI_PADDING OFF  
GO